#!/usr/bin/bash

if [[ -z $1 ]]; then
	echo "error: missing site name"
	echo "usage: mksite SITENAME"
	exit 1
fi

if [[ $USER != "root" ]]; then
	echo "error: script must be run as root"
	exit 1
fi

if [[ ! -e /usr/share/mksite/site.template.conf ]]; then
	echo "error: missing site.template.conf"
	exit 1
fi

SITENAME=$(basename $1)

# Créer un nom de domaine
grep $SITENAME.lan /etc/hosts > /dev/null
if [[ $? -ne 0 ]]; then
	echo "127.0.0.1	$SITENAME.lan" >> /etc/hosts
fi

# Créer un contenu
mkdir -p /var/www/$SITENAME
echo "Bienvenue sur $SITENAME.lan" > /var/www/$SITENAME/index.html

# Configurer le server web
export SITENAME
cat /usr/share/mksite/site.template.conf | \
	envsubst > /etc/apache2/sites-available/$SITENAME.conf
a2ensite $SITENAME > /dev/null
systemctl reload apache2
